### ISSUE TITLE
Adv code run into some kind of problem

### ISSUE THREAD

**Issue by TheOnlylight** [microsoft/vert-papers#17]
The program threw the exceptions saying that it cannot find certain output and result file, how should i solve this

**Comment by TheOnlylight** [comment]
![image](https://user-images.githubusercontent.com/24605645/148526894-a26b9f53-e24b-4152-84c9-d944e6564df8.png)
The bug look like this and there's no pth within the file

**Comment by iofu728** [comment]
@TheOnlylight, It seems that there're no data in the `data/` folder. Due to the copyright, we only list sample data in the repo. You should follow the descript of the dataset and preprocess script to prepare the dataset and put them in the `data/` folder.
