### ISSUE TITLE
In the CAN NER

### ISSUE THREAD

**Issue by eatinghungry** [microsoft/vert-papers#18]
self.add_module('feature_embeds_{}'.format(0), embeds)
 self.add_module('feature_embeds_{}'.format(1), soft_seg)

while i >=2 it would raise error:

feature_embed_data = batch_x[:, :, i]
feature_embeds = getattr(self, 'feature_embeds_{}'.format(i))

and in the preprocess py ,there are some index out of range error.

**Comment by tellarin** [comment]
Please provide more details of what you're trying to do and the exact problem. The CAN-NER code runs fine for me.
