### ISSUE TITLE
《Decomposed Meta-Learning for Few-Shot Named Entity Recognition》 code path 404

### ISSUE THREAD

**Issue by lvminghan1997** [microsoft/vert-papers#20]

**Comment by QianhuiWu** [comment]
Thanks for your interest in our paper and code!
We are going through the review process of open source code. This link will be available when the review is completed. : )

**Comment by QianhuiWu** [comment]
> _No description provided._

The code is available now!

**Comment by lvminghan1997** [comment]
Thank You ！！
