### ISSUE TITLE
Which line is the code of Meta learning in Decomposed meta NER

### ISSUE THREAD

**Issue by dongguanting** [microsoft/vert-papers#37]
May I ask which line is the related code of the prototype network and MAML? I read your code carefully but do not find them.

**Comment by iofu728** [comment]
Hi @dongguanting, in fact, the whole logic can be found by analyzing the [running script](https://github.com/microsoft/vert-papers/blob/master/papers/DecomposedMetaNER/scripts/run.sh).
You can find MAML logic in [`forward_meta` function](https://github.com/microsoft/vert-papers/blob/master/papers/DecomposedMetaNER/learner.py#L257), both inner loop and outer loop.
You can also find ProtoNet in the `forwad_wuq` function https://github.com/microsoft/vert-papers/blob/master/papers/DecomposedMetaNER/modeling.py#L125. We use a packaged `nn.embedding` class `EntityTypes` to memorize type embeddings.

**Comment by dongguanting** [comment]
Hi @[iofu728](https://github.com/iofu728), Thank you for your answer! But I still have another question which bothers me. I find that the model will backward twice during [forward_meta function](https://github.com/microsoft/vert-papers/blob/master/papers/DecomposedMetaNER/learner.py#L257), namely inner update function and outer forward_wuqh. I think it may be related to MAML method, but why split into two processes to backward?

**Comment by iofu728** [comment]
Hi @dongguanting, this is how MAML does it. You can refer the [MAML paper](https://arxiv.org/abs/1703.03400) or other tutorials like [AAAI21 MetaLearning Tutorial](https://sites.google.com/mit.edu/aaai2021metalearningtutorial).

In short, for the inner update part, the model fine-tunes specific task _i_ data based on original model parameter $\theta$ (Inner update bp). After an inner update step in the meta-train dataset, the model will store each loss of the meat-test dataset. At the end of each inner update step, the model recovers to the original parameter _$\theta$_.
The output update bp will calculate after all of the tasks' inner updates. The second-order derivative will make the model pay more attention to the transfer of knowledge between different tasks.

**Comment by wjczf123** [comment]
Hi, I also have similar question. Is there any parameter to control meta-learning? I want to reproduce the results of 1) Ours w/o MAML.

**Comment by iofu728** [comment]
Hi @wjczf123, yeah, the code also supports full supervision mode(w/o MAML). You can set the [`use_supervise`](https://github.com/microsoft/vert-papers/blob/master/papers/DecomposedMetaNER/main.py#L554) argument to `True`, which will call the `forward_supervise` function instead of `forward_meta`.

**Comment by wjczf123** [comment]
Nice! Thank you very much.
