### ISSUE TITLE
ask for some  problems？

### ISSUE THREAD

**Issue by topDreamer** [microsoft/vert-papers#4]
请问Seg Embedding到底是如何计算后和char拼接的？论文和代码好像也不一致～
另外，还遇到两个问题，第一个是想咨询下输入数据格式是怎么样的，能否给下样例数据（因为直接输入(char tag)是不可以的），因为看数据处理的过程，看不到seg信息是如何添加的；
第二个问

**Comment by lvjiujin** [comment]
> 请问Seg Embedding到底是如何计算后和char拼接的？论文和代码好像也不一致～
> 另外，还遇到两个问题，第一个是想咨询下输入数据格式是怎么样的，能否给下样例数据（因为直接输入(char tag)是不可以的），因为看数据处理的过程，看不到seg信息是如何添加的；
> 第二个问

这个论文的做法，我的理解就是根据BMES 标签信息构建出分词的边界信息。然后根据分词信息（就是一个一个词）从预训练的word embedding 中查找到对应的词向量，然后和char embedding 进行拼接。这仅仅是我自己的理解不知道正确不？代码注释很少，看起来真费劲，预处理过程也没有提供，不给力呀。

**Comment by wgx998877** [comment]
+ https://github.com/microsoft/vert-papers/issues/3#issuecomment-856391721
