### ISSUE TITLE
A detailed question about meta-testing

### ISSUE THREAD

**Issue by wjczf123** [microsoft/vert-papers#41]
Hi, @iofu728. It seems that you fine-tune model on dev to choose a model. This means that the model also uses dev to train. I'm not sure my understanding is true.

**Comment by iofu728** [comment]
Hi @wjczf123, in fact, the model can use the support set data in each task in the few-shot scenario like the N-ways K-shots setting.
As the paper section 3.1.2 mentions, we follow this setting and fine-tune the model from the meta-trained model only using the own support set data in each meta-test task. And using the task-specific model to evaluate in the meta-test query set.

**Comment by wjczf123** [comment]
OK. Thanks.
