### ISSUE TITLE
一个关于数据处理的问题

### ISSUE THREAD

**Issue by ZXY-Hobby** [microsoft/vert-papers#5]
你好！请问data/en-train-processed.txt 是什么格式

**Comment by QianhuiWu** [comment]
> 你好！请问data/en-train-processed.txt 是什么格式

每行对应于一个 training example，`'|'` 之前是经 `BertTokenizer` 处理后的 input sequence, 之后是与 input sequence 中每个 token 相应的 label。

可以去`preprocessor.py` 中的`_prepare_data`函数 check：

`item = ' '.join(['[CLS]'] + tokens + ['[SEP]']) + '\t|\t' + ' '.join(['[CLS]'] + labels + ['[SEP]'])`

**Comment by ZXY-Hobby** [comment]
明白了，感谢您的回复！
这里还想向您请教一个我有点困惑的地方，论文中提到：
we propose to fine-tune the model by converting the minimal-resource cross-lingual transfer problem into a low-resource learning problem.
这里的对于minimal-resource和low-resource的情况如何界定，也就是具体多少数据是称为minimal-resource、low-resource？因为从dataset statistics中可看出，实验中采用的每个dataset数据量都很大，以此为基础的实验结论是否会掩盖元模型实际应用于few shot场景的性能？

**Comment by QianhuiWu** [comment]
> 明白了，感谢您的回复！
> 这里还想向您请教一个我有点困惑的地方，论文中提到：
> we propose to fine-tune the model by converting the minimal-resource cross-lingual transfer problem into a low-resource learning problem.
> 这里的对于minimal-resource和low-resource的情况如何界定，也就是具体多少数据是称为minimal-resource、low-resource？因为从dataset statistics中可看出，实验中采用的每个dataset数据量都很大，以此为基础的实验结论是否会掩盖元模型实际应用于few shot场景的性能？

minimal resource对应于目标语言没有标注数据的情况，也有其他论文采用"zero resource"的说法，但考虑到源语言是有标注数据的，因此论文中采用了“minimal resource”。
low resource则表示目标语言有少量标注数据的情况，例如“Discussion: Extend to Low-Resource Cross-Lingual NER”部分的setting。

具体到“we propose to fine-tune the model by converting the minimal-resource cross-lingual transfer problem into a low-resource learning problem”这句话，是因为在minimal resource (i.e., zero resource)的setting下，每个target-language test example和它的 k 个source-language similar examples一起，可以看做是一个low-resource(这里可以理解为 k-shot)的问题。
