### ISSUE TITLE
[CAN-NER] What's the 'seg'？

### ISSUE THREAD

**Issue by actforjason** [microsoft/vert-papers#6]
`model/data_process.py`
```python
for index, line in enumerate(lines):
    text = line.strip().split(" ")
    word = text[0][0]
    seg = text[0][1]
    tag = text[1]
```
What's the `seg`？In the train data, there isn't `seg`!

> 吴 B-NAME
重 M-NAME
阳 E-NAME
， O
中 B-CONT
国 M-CONT
国 M-CONT
籍 E-CONT
， O
大 B-EDU
学 M-EDU
本 M-EDU
科 E-EDU

**Comment by lvjiujin** [comment]
In the label tags, you can create segmentation. such as 
吴 B-NAME
重 M-NAME
阳 E-NAME
， O
can get “吴重阳” 。 This is just my guess. B, M, E, S are the boundary information. '-NMAE' is the entity, we can form the seg.

**Comment by wgx998877** [comment]
In the original dataset, besides of NER labels, they provide the word segmentation(chunking) information in the word line as well, so here seg means the segmentation index of each word.
For the data without the segmentation info, you could utilize the method/tools mentioned from paper, or leverage other Chinese segmentation tools to generate those seg info.

**Comment by wgx998877** [comment]
+ https://github.com/microsoft/vert-papers/issues/3#issuecomment-856391721
