### ISSUE TITLE
Fail to reproduce the f1 score for dataset Cross-Dataset

### ISSUE THREAD

**Issue by green-fruit** [microsoft/vert-papers#68]
Hi @iofu728 , thanks for your README file, I have already reproduced the f1 score for Few-NERD V6. However, when it comes to Cross-Dataset, I cannot reproduce the result as presented in paper. 
For example, for setting Wiki 1-shot, the result is 14.837,4.236,6.591,25.452,7.266,11.305,34.928,34.928,34.928,15.006,3.800,6.064 if I do not modify any hyperparameter. Then I set the finetune step to 30 and 20 according to A.3 Additional Implementation Details, I also change the inner_lambda_max_loss and the type_threshold, the final result is 17.484,12.891,14.840,35.528,26.194,30.155,41.734,41.734,41.734,19.475,12.240,15.032. It looks better but there is still some distance from 17.54. 
Could you please tell me where is the problem (meta training or meta test)? Have you recorded the experimental hyperparameters for Cross-Dataset?
Thanks.

**Comment by iofu728** [comment]
The cross-domain datasets require more precise hyper-parameter tuning. According to my experimental record, the hyper-parameters used are as follows: 2/16/3, which denotes the stage using inner_steps=2, inner_size=16, and max_ft_steps=3. I have included two-stage (span and type) and other parameters in the table.

||News|Wki|Social|Mixed|
|-|-|-|-|-|
|1-shot|2/16/50-2/16/3-MaxLoss-1/-1-10/30-BIOES-Viterbi 1e-4|2/16/40-2/16/20-MaxLoss-1/-1-10/30-BIOES-Viterbi 1e-4	|2/16/40-2/16/10-MaxLoss-1/-1-10/30-BIOES-Viterbi 1e-4	|2/16/40-2/16/20-MaxLoss-1/-1-10/30-BIOES-Viterbi 1e-4|
|5-shot|2/16/40-2/16/20-MaxLoss-1/-1-10/30-BIOES-Viterbi 1e-4	|2/16/40-2/16/20-MaxLoss-1/-1-10/30-BIOES-Viterbi 1e-4	|3/16/40-2/16/3-MaxLoss-1/-1-10/30-BIOES-Viterbi 1e-4	|2/16/40-2/16/20-MaxLoss-1/-1-10/30-BIOES-Viterbi 1e-4|

I also use smaller eval_every_meta_steps, such as 20 or 50, and a smaller max_meta_steps of 300/200 to avoid overfitting.

You can refer to them, I hope it will be helpful for you.

**Comment by green-fruit** [comment]
Thanks for your reply @iofu728 , it helps me a lot. Have a nice holiday!

**Comment by iofu728** [comment]
Hi @lvminghan1997, the 10/30 should be the similar_k/inner_similar_k in the Type Stage. However, I think the effect might be caused by the early stop step. You can try setting eval_every_meta_steps to 20 or 50, and a smaller max_meta_steps of 300/200.

**Comment by sehbe** [comment]
@green-fruit Hello! How did you reproduce this result for Few-NERD V6? I haven't modified the source code, I cannot reproduce the resul. I have been studying this paper for a long time. Could you please help me? 
Thanks!

**Comment by green-fruit** [comment]
> @green-fruit Hello! How did you reproduce this result for Few-NERD V6? I haven't modified the source code, I cannot reproduce the resul. I have been studying this paper for a long time. Could you please help me? Thanks!

+q 1905309844 if necessary

**Comment by iofu728** [comment]
> > Hi @lvminghan1997, the 10/30 should be the similar_k/inner_similar_k in the Type Stage. However, I think the effect might be caused by the early stop step. You can try setting eval_every_meta_steps to 20 or 50, and a smaller max_meta_steps of 300/200.
> 
> Hi @iofu728，i think the effect might be caused by the --lr_finetune,the parameters 1e-4 in the table represent lr_finetune or lr_inner ?

@lvminghan1997, 1e-4 is the value for the lr_finetune parameter.

**Comment by iofu728** [comment]
> @green-fruit Hello! How did you reproduce this result for Few-NERD V6? I haven't modified the source code, I cannot reproduce the resul. I have been studying this paper for a long time. Could you please help me? Thanks!

Hi @sehbe, please provide more detail about your experiments, like logs, and running enlivenment.
