### ISSUE TITLE
CAN-NER, data process problem

### ISSUE THREAD

**Issue by lvjiujin** [microsoft/vert-papers#7]
can you offer the data files in the data folder like the following:
`
 "./data/embeds",
  "./data/embedding/embeds",
  "./data/embedding/word2vec.sgns.weibo.onlychar",
  "./data/embedding/fasttext.cc.zh.300.vec.onlychar",
  "./data/embedding/glove.6B.100d.english.txt",
  "./data/embedding/glove.6B.300d.english.txt"]
`

**Comment by wgx998877** [comment]
for last four, seems they are common and easy to find from:
https://github.com/Embedding/Chinese-Word-Vectors
https://fasttext.cc/docs/en/crawl-vectors.html
https://nlp.stanford.edu/projects/glove/

Please consider the embedding settings from paper.

**Comment by wgx998877** [comment]
+ https://github.com/microsoft/vert-papers/issues/3#issuecomment-856391721

**Comment by lvjiujin** [comment]
thank you very much. Now, I will have a try for your paper code.
